services:
  db:
    image: postgres:16
    container_name: book_finder_db
    environment:
      POSTGRES_DB: book_finder
      POSTGRES_USER: bf_user
      POSTGRES_PASSWORD: bf_pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
