spring:
  application:
    name: book_finder

  datasource:
    url: jdbc:postgresql://localhost:5432/bf_database
    username: author
    password: Q9vR8k2pLsT4

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
