spring:
  application:
    name: book_finder

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/bf_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}