spring:
  application:
    name: book_finder

  datasource:
    url: jdbc:postgresql://localhost:5432/bf_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver # Good to add for clarity

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS:86400000}