CREATE TABLE users (
                       user_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username       VARCHAR(50)  NOT NULL UNIQUE,
                       email          VARCHAR(254) NOT NULL UNIQUE,
                       password_hash  TEXT        NOT NULL,
                       bio            TEXT,
                       join_date      DATE        NOT NULL DEFAULT CURRENT_DATE,
                       is_banned      BOOLEAN     NOT NULL DEFAULT FALSE
);
