spring.application.name=book-finder

spring.datasource.url=jdbc:postgresql://localhost:5432/book_finder
spring.datasource.username=bf_user
spring.datasource.password=bf_pass

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
